### ISSUE TITLE
About ESKF::CorrectWithIterators

### ISSUE THREAD

**Issue by XuShengpan** [Enigmatisms/RMESKF#4]
It seems that it will do nothing update in each iteration，you forget x += dx ?

**Comment by Enigmatisms** [comment]
Thanks for paying attention to this repo. This repo is out-dated and my research interest has been oriented to rendering since 2022. I've already forgotten every related detail so it's sorry to tell you that I cannot asnwer your question. However, this repo is actually based on the code of [infinity1096/eskf_localization](https://github.com/infinity1096/eskf_localization), which might help since I believe their original code should work.
